{
 "title": "Wykop Stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Fetching time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "wykop_fetch_duration_seconds{exported_job=\"vectorizer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetching posts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "wykop_posts_total{exported_job=\"vectorizer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pluses histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "wykop_post_pluses{job=\"vectorizer\"}",
     "legendFormat": "{{author}}{{post_id}}"
    }
   ]
  },
  {
   "title": "Detected languages",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "wykop_language_detected_total{job=\"wykop_scraper\"}",
     "legendFormat": "{{lang}}"
    }
   ]
  }
 ]
}