apiVersion: v1
kind: Secret
metadata:
  name: mini-project-secrets
type: Opaque
stringData:
    WYKOP_API_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Inc1Zjg5NGJhZTlmNWFmMWZiYzNlMTY1ODRjZmM5MzY3NjIiLCJ1c2VyLWlwIjoiMTQ5NzM2ODQ2MyIsInJvbGVzIjpbIlJPTEVfQVBQIl0sImFwcC1rZXkiOiJ3NWY4OTRiYWU5ZjVhZjFmYmMzZTE2NTg0Y2ZjOTM2NzYyIiwiZXhwIjoxNzQ5NjcyNDg4fQ.cTQtznliohfCSW-GYvFvjOH-rG5TQ8SR-NUViwz5i1M"
  
    REDIS_HOST: "redis://mini-project-redis-master:6379/0"
    POSTGRES_HOST: "postgresql://postgres:postgres@postgres/postgres"
    PTG_HOST: "pushgateway://mini-project-prometheus-pushgateway:9091"
    MONGO_HOST: "mini-project-mongo:27017"
  
    REDASH_COOKIE_SECRET: 8120d8e36374c3f68d3208141d21034e235fbcbb42ffce048259fbd7d3d563c3
    REDASH_DATABASE_URL: "postgresql://postgres:postgres@postgres/wykopdb"
    REDASH_REDIS_URL: "redis://mini-project-redis-master:6379/0"
    MONGO_INITDB_DATABASE: "wykopdb"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"