apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    app: {{ include "mongo.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mongo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongo.name" . }}
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongo.username | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongo.password | quote }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo.database | quote }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}